# Generated by Django 3.2 on 2021-05-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.TextField(null=True, verbose_name='プロフィール'),
        ),
    ]
