# Generated by Django 3.2 on 2021-07-14 02:39

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210713_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='users/default.png', upload_to=accounts.models.user_image_path),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
